ad.created.draft=Ad draft created successfully.
ad.submitted=Ad submitted successfully.
ad.approved=Ad approved successfully.

ad.error.invalid_status=This ad cannot be processed in its current state.
ad.error.field_required=Ad ''{0}'' field is required.
ad.error.exceeded_limit=Field ''{0}'' exceeds maximum length. Limit is {1}.
ad.error.deleted=Deleted ad cannot be modified.
ad.error.id_already_assigned=Id is already assigned.
ad.error.assigned_id_must_be_assigned=Assigned id must be assigned.
ad.error.invalid_state_for_initialization=Ad is not in a valid state for initialization.
ad.error.id_must_be_assigned={0} must be assigned.
