location.error.field_required={0} ''{1}'' field is required.
location.error.country_iso=Country ISO code must be a 2-letter code.
location.error.invalid_slug=Invalid slug.
location.error.country_not_found=Country does not exist.
location.error.province_not_in_country=Province does not exist in the given country.
location.error.city_not_in_province=City does not exist in the given province.
location.error.neighbourhood_not_in_city=Neighbourhood does not exist in the given city.
location.error.point_outside_neighbourhood=Point must be inside the selected neighbourhood.
