server:
  port: 9090

logging:
  level:
    com.nextbuy.passport.*: DEBUG
    org.hibernate.SQL: DEBUG

spring:
  profiles:
    active: dev

  application:
    name: "passport"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/passport
    username: "passport"
    password: "passport@@p@sswd"

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  data:
    redis:
      client-name: passport
      host: localhost
      port: 6379
      database: 0
      client-type: lettuce

  flyway:
    enabled: true
    locations: classpath:db/migration
    table: flyway_passport
    #    lock-retry-count: 20
    #    baseline-on-migrate: true
  main:
    banner-mode: off
#    validate-on-migrate: true


jwt:
  secret: "xTmCfNhvKwErW4qixunjfNRyAts4frpY"
  access-token-expiry: 30
  refresh-token-expiry: 40


bucket4j:
  redis:
    database: 1
  rate-limit:
    login:
      ip:
        capacity: 5          # max attempts
        refill-amount: 5     # refill to this amount
        refill-duration: 10   # seconds
      user:
        capacity: 5
        refill-amount: 5
        refill-duration: 10
